docs: add Gnars Contracts Explained (BOUNTY)
gnars-dao/gnars-docs pull request #21
Opened 2024-05-16 22:42 UTC by Reubenstein

https://docs.google.com/spreadsheets/d/1Jg1k35fZunfPgKXad9x8P7coXy76ZtD16VhvkAJyQcA/edit#gid=0

2024-05-17 02:37 UTC, Reubenstein commented on package.json
> +    "node": ">=18",
I made this change because Vercel is going to deprecate Node 16 on June 15th so we should get ahead of that https://vercel.com/changelog/node-js-14-and-16-are-being-deprecated

2024-05-27 22:34 UTC, 0xMillz approved these changes
LGTM

2024-05-29 02:05 UTC, asmattic commented
Add me as reviewer

2024-05-29 02:49 UTC, asmattic requested changes
Mainly just some link changes. 

Sidenote: as we grow the docs, internal linking within/between doc pages should be in our guidelines for ease of navigation.

2024-05-29 02:49 UTC, asmattic commented on docs/For Devs/contracts-explained.mdx
> +| [1. Token](https://basescan.org/address/0x880Fb3Cf5c6Cc2d7DFC13a993E839a9411200C17)              | This is the Gnars ERC-721 NFT contract. Each NFT represents membership in the DAO, and the number
Add the link for ERC-721 for reference https://ethereum.org/en/developers/docs/standards/tokens/erc-721/

2024-05-29 02:49 UTC, asmattic commented on docs/For Devs/contracts-explained.mdx
> +Gnars DAO is a suite of five smart contracts on the BASE Ethereum Layer 2 chain. Membership and voting power in the DAO are represented by NFTs, which are minted and distributed in a perpetual auctio
on [BASE](https://www.base.org/), an [Ethereum Layer 2 chain](https://ethereum.org/en/layer-2/)

2024-05-29 02:49 UTC, asmattic commented on docs/For Devs/contracts-explained.mdx
> +Gnars DAO is a suite of five smart contracts on the BASE Ethereum Layer 2 chain. Membership and voting power in the DAO are represented by NFTs, which are minted and distributed in a perpetual auctio
So there's easy references to both.

2024-05-29 02:49 UTC, asmattic commented on docs/For Devs/contracts-explained.mdx
> +| [2. Auction House](https://basescan.org/address/0x494Eaa55ECF6310658B8fC004b0888DCB698097f)      | This contract acts as a generation and distribution mechanism for new Gnars NFTs, minting as many
Remove the numbers on the Contract side of the table, it just adds clutter.

2024-05-29 02:49 UTC, asmattic commented on docs/For Devs/contracts-explained.mdx
> +The Builder protocol is a tool that was used to migrate Gnars DAO from Ethereum Layer 1 to BASE Layer 2. The following values are set by Builder at the protocol level and cannot be changed:
Add https://nouns.center/intro, or nouns.build to link to the builder protocol.

2024-05-29 04:56 UTC, asmattic approved these changes

2024-05-29 04:57 UTC, asmattic commented
Good to go

2024-05-29 10:21 UTC, merged